### PR TITLE
Added Ranking button to see ranking all player

### PR DESCRIPTION
**Pull request by rendi12345678**
i wanted to add the backend server with node + express

### CODE REVIEW

**Comment by MUYANGGUO** [comment]
> i wanted to add the backend server with node + express

Hmmm, what's the intention here? do you want to share more details of the backend set up? Or do you want to let our users use your backend?

**Comment by MUYANGGUO** [comment]
> i wanted to add the backend server with node + express

@rendi12345678 please see my reponse in your another pull request, thanks for the interests tho, FEEL FREE TO CONTACT ME IN DISCORD FOR BACKEND.

**Comment by rendi12345678** [comment]
> > i wanted to add the backend server with node + express
> 
> Hmmm, what's the intention here? do you want to share more details of the backend set up? Or do you want to let our users use your backend?

yes i want to give my backend with node js+ express js

**Comment by MUYANGGUO** [comment]
> > > i wanted to add the backend server with node + express
> 
> > 
> 
> > Hmmm, what's the intention here? do you want to share more details of the backend set up? Or do you want to let our users use your backend?
> 
> 
> 
> yes i want to give my backend with node js+ express js

happy to review the backend set up pull request.
Will take a look once it is done. Probably hold off the frontend PR merging until the backend db schema, deployment, and api design s are consolidated and reviewed. Feel free to tag me for the PR review.

**Pull request closed without merging**
