### PR TITLE
Added login and logout user and allowed guest to play without login

### PR DESCRIPTION
**Pull request by rendi12345678**

### CODE REVIEW

**Comment by rendi12345678** [comment]
sc-login-page

**Comment by rendi12345678** [comment]
sc-user-profile

**Comment by rendi12345678** [comment]
Those are that i have made :)

What is your opinion sir ?

**Comment by rendi12345678** [comment]
WhatsApp Image 2023-12-02 at 21 53 26

I am going to make an User Profile like that sir!

**Comment by MUYANGGUO** [comment]
Pretty cool!
Thanks for handling the themes.
Will take a close look this week.

**Comment by MUYANGGUO** [comment]
Can we add a go back button in the sign up and login form that would navigate back to home page if user decided not to.

**Pull request closed without merging**
